### ISSUE TITLE
Grupo Slack

### ISSUE THREAD

**Issue by pabcargar2** [AgoraUS1516/G03#2]
He creado un grupo en Slack para la gestión de las comunicaciones. La dirección es https://athenticateagoraus.slack.com/

Necesito vuestros correos para invitaros.

**Comment by josnavmar** [comment]
josnavmar@gmail.com ------> JOSE MANUEL NAVARRO MARQUEZ

**Comment by Sergio20** [comment]
sergiocarrascosa18@gmail.com  ------> Sergio Carrascosa Oliva

**Comment by Fuerte94** [comment]
fuerte94@gmail.com -------------------> Jorge Rodríguez Fuerte

**Comment by DarkSoul7** [comment]
alejandro.tortolero7@gmail.com -------------> Alejandro Tortolero Martín

**Comment by Ossyriand** [comment]
giulianodai@hotmail.com  -- >  Julian Mayer Álvarez (Ossyriand)
