### ISSUE TITLE
Fallo petición Api

### ISSUE THREAD

**Issue by roberjc** [AgoraUS1516/G03#5]
El método checkToken de vuestra Api mapea la respuesta a esa petición en formato Json, pero he observado que falla al declarar que el tipo de contenido sea json. Concretamente, el fallo se debe a la línea 104 de la clase index.php.

**Comment by pabcargar2** [comment]
Gracias compañero, no nos habiamos fijado en el error, lo solucionaremos lo antes posible.

**Comment by pabcargar2** [comment]
Solucionado.
